Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/07/2022
Var
num :real
Inicio
escreval("Digite um numero qualquer")
leia(num)
//processamento

se (num mod 2 = 1) entao
   escreval("O número é impar")
senao
   escreva("O número é par")
fimse
Fimalgoritmo