Algoritmo "volei"
Var
// Seção de Declarações das variáveis
i,a : real


Inicio
//entrada
escreval("Digite seu idade")
leia(i)
escreval("Digite sua altura")
leia(a)

//processamento
  se(idade>=18)entao


  senao
  escreval("Muito novo para competi")

  fimse

  se(altura>=1.75)entao
  escreval("Você pode competir")

  senao
  escreval("Muito baixo para competir")

  fimse

Fimalgoritmo