Algoritmo "For"
Var
// Seção de Declarações das variáveis 
i,acu:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("LAÇO PARA INCREMENTO")
para i de 1 ate 30 faca
     escreval(i)
fimpara
escreval("LAÇO PARA DECREMENTO")
para i de 30 ate 0 passo -2 faca
     escreval(i)
fimpara
para i de 0 ate 20 faca
     acu <- acu+i
     escreval("acumulando...")
     escreval(acu)
fimpara
Fimalgoritmo
