algoritmo "media_estoque"
// Função :  medir a media de ukm estoque
// Autor :   Victor Marques
// Data : 26/04/2022
var
qntmi, qntma, media:real
inicio
//entrada
escreval("Digite a quantidade minima de estoque")
leia(qntmi)
escreval("Digite a quantidade maxima de estoque")
leia(qntma)
//processamento
media<-(qntmi+qntma)/2
//saida
escreval("A media de estoque é",media)
fimalgoritmo
